import { Footer, Header } from "@/shared/components";
import "./globals.scss";
import "swiper/css";
import "swiper/css/navigation";
import type { Metadata } from "next";
import { ContextProvider, StyledComponentsRegistry } from "@/shared/providers";
import "@/shared/services/system/storage.service";

export const metadata: Metadata = {
  title: "Хмельницьк залізобетон",
  description: "Generated by create next app",
};

interface IProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: IProps) {
  return (
    <html lang="en">
      <ContextProvider>
        <body>
          <Header />
          <main className="main">{children}</main>
          <Footer />
        </body>
      </ContextProvider>
    </html>
  );
}
