import { Breadcrumbs } from "@/shared/components";
import React from "react";

import { NewsList } from "./components";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Новини",
  description: "Generated by create next app",
};

export default function News() {
  return (
    <>
      <Breadcrumbs />
      <section>
        <NewsList />
      </section>
    </>
  );
}
